print('Notas do aluno')
a=input('Digite o nome do aluno: ')
m=input('Digite o nome da matéria: ')
n1=float(input('Digite o valor da nota: '))
n2=float(input('Digite o valor da nota: '))
print(f'A nota final do aluno será {(n1+n2)/2 :.1f}')